name: Notify `Full Stack Open 2020 Progress` channel of any pushes you made to master
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Notify Telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Send a push message with Github info to channel
        uses: appleboy/telegram-action@master
        env:
          CURRENT_COURSE_YEAR: 2020
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          args: | 
            ${{ secrets.TELEGRAM_USER }} 
            ${{ github.event_name }}
            ![Notify `Full Stack Open 2020 Progress` channel of any pushes you made to master](https://github.com/tagraf/FullStackOpen/workflows/Notify%20%60Full%20Stack%20Open%202020%20Progress%60%20channel%20of%20any%20pushes%20you%20made%20to%20master/badge.svg?event=status)

            https://github.com/${{github.repository}} 
                 
